version: '3'

networks:
<<<<<<< HEAD
<<<<<<< HEAD
  L10D_network:

services:
  app:
    container_name: L10D-app
=======
  11Aug_network:

services:
  app:
    container_name: 11Aug-app
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
  11Aug_network:

services:
  app:
    container_name: 11Aug-app
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - artisan
      - mysql
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  mysql:
    container_name: L10D-mysql
=======
      - 11Aug_network

  mysql:
    container_name: 11Aug-mysql
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  mysql:
    container_name: 11Aug-mysql
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: foundation
      MYSQL_USER: seldon
      MYSQL_PASSWORD: trantor
      MYSQL_ROOT_PASSWORD: psychohistory
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  php:
    container_name: L10D-php
=======
      - 11Aug_network

  php:
    container_name: 11Aug-php
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  php:
    container_name: 11Aug-php
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/html:delegated
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  redis:
    container_name: L10D-redis
=======
      - 11Aug_network

  redis:
    container_name: 11Aug-redis
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  redis:
    container_name: 11Aug-redis
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  composer:
    image: composer:latest
    container_name: L10D-composer
=======
      - 11Aug_network

  composer:
    image: composer:latest
    container_name: 11Aug-composer
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  composer:
    image: composer:latest
    container_name: 11Aug-composer
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  npm:
    image: node:current-alpine
    container_name: L10D-npm
=======
      - 11Aug_network

  npm:
    image: node:current-alpine
    container_name: 11Aug-npm
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  npm:
    image: node:current-alpine
    container_name: 11Aug-npm
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    volumes:
      - ./src:/var/www/html
    ports:
      - '3000:3000'
      - '3001:3001'
      - '5173:5173'
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  artisan:
    container_name: L10D-artisan
=======
      - 11Aug_network

  artisan:
    container_name: 11Aug-artisan
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  artisan:
    container_name: 11Aug-artisan
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  cron:
    container_name: L10D-cron
=======
      - 11Aug_network

  cron:
    container_name: 11Aug-cron
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network

  cron:
    container_name: 11Aug-cron
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    build:
      context: ./dockerfiles
      dockerfile: cron.dockefile
    volumes:
      - ./src:/var/www/html
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network

  # python:
  #   container_name: L10D-python
=======
=======
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
      - 11Aug_network

  # python:
  #   container_name: 11Aug-python
<<<<<<< HEAD
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: python.dockerfile
  #   volumes:
  #     - ./src:/var/www/html
  #   networks:
<<<<<<< HEAD
<<<<<<< HEAD
  #     - L10D_network

  phpmyadmin:
    container_name: L10D-phpmyadmin
=======
  #     - 11Aug_network

  phpmyadmin:
    container_name: 11Aug-phpmyadmin
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
  #     - 11Aug_network

  phpmyadmin:
    container_name: 11Aug-phpmyadmin
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    ports:
      - 8081:80
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - L10D_network
=======
      - 11Aug_network
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130
=======
      - 11Aug_network
>>>>>>> 034ea41fb4f7f090b5ab1428a50bc5c2e6068130

volumes:
  db_data:
    driver: local
